### ISSUE TITLE
Can only scroll backwards in idmode number for NA exclusive cards

### ISSUE THREAD

**Issue by ethannp** [TsubakiBotPad/padbot-cogs#146] opened 2020-10-18 12:51 UTC
go into ^idmode number
try ^idna 4953 (or just ^id 4953)
you can only scroll backwards (left) through the ids and not right

**Comment by RheingoldRiver** [comment] 2020-10-18 12:52
duplicate of #123

**Comment by RheingoldRiver** [comment] 2020-10-18 12:52
wait I read this too fast sorry

**Comment by RheingoldRiver** [comment] 2020-10-18 13:25
closed by #147

**Closed** 2020-10-18 13:26 UTC
